name: Sequential Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
        dotnet-version: '8.0.x'
      - name: Build project
        run: dotnet build src/YourProject.csproj
test:
  needs: build
  runs-on: ubuntu-latest
steps:
  - name: Checkout code
    uses: actions/checkout@v4
  - name: Run tests
    run: dotnet test src/YourProject.Tests.csproj
